---
title: "pred_dbem"
author: "Juliano Palacios Abrantes"
date: "2023-10-24"
output: html_document
---

```{r setup, include = F}

# source(here::here('./functions/function_list.R')) #I took these from mpa_c_toe
# source(here::here('./functions/figures_fx.R')) #Functions for creating figures

library(MyFunctions)

my_lib(c(
  # For grid estimation and species selection
  "spatialEco","tidyverse", "geosphere","raster","units","matrixStats","sf","rmapshaper", "igraph",
  # For collaborative ease
  "here",
  "readr",
  "janitor",
  # For nitce figures
  "hrbrthemes",
  "viridis"
))

# For grid e
# Fix new updates of sf package
sf::sf_use_s2(use_s2 = FALSE)

select <- dplyr::select



# Global color pallets standardization

# Status pallet
status_pallet <- c("#00A08A", # Open
                   "#046C9A", # Protected
                   "#F98400" # Surrounding
) 

# SSP pallet
ssp_pallet <- c("#5BBCD6", #126
                "#FF0000" #585x
)

# Scenario pallet
scenario_pallet <- c("#02401B", # S1
                     "#FD6467", # S2
                     "#B6854D" # S3
)


# Change paths to your computer

data_path <- "~/Library/CloudStorage/GoogleDrive-jepa88@gmail.com/My Drive/lenfest_mpa_project/data/"


results_path <- "~/Library/CloudStorage/GoogleDrive-jepa88@gmail.com/My Drive/lenfest_mpa_project/manuscripts/scenarios_paper/results"
```



# Determine grid

```{r}

# Load SAU SF
sau_sf <- my_sf("SAU") %>% 
  filter(name %in% c("Costa Rica (Pacific)","Colombia (Pacific)","Panama (Pacific)","Galapagos Isl. (Ecuador)", "Ecuador"))





# Load Grid data
grid_path <- paste0(data_path,"spatial/gridded/all_mpa_grid_fe.csv")
mpas_grid <- read_csv(grid_path) %>% 
  rename(mpa_abrev = mpa) %>% 
  distinct()

cmar_grid <- my_data("dbem_coords") %>% 
  filter(lat < 10 & lat > -10 & lon > -100 & lon < -70) %>% 
  left_join(mpas_grid) %>% 
  left_join(my_data("sau_index")) %>% 
  mutate(status = ifelse(is.na(status),"non_protected",status),
         region = ifelse(is.na(mpa_abrev),eez_name,mpa_abrev)
  ) %>% 
  filter(!region %in% c("Colombia (Caribbean)","Panama (Caribbean)","Costa Rica (Caribbean)","El Salvador","Nicaragua (Pacific)","Peru","Venezuela"),
         !is.na(eez_name))

ggplot(cmar_grid) +
  geom_tile(
    aes(
      x = lon,
      y = lat,
      fill = status
    )
  ) +
  my_land_map()+
  geom_sf(data = sau_sf, aes(), fill = "transparent") +
  coord_sf(
    xlim = c(-95,-77),
    ylim = c(-4,9)
  )

# facet_wrap(~mpa_abrev)




```

```{r}
file_to_read <- str_sub(list.files(my_path("R","c6ipsl85F1sq"),full.names = F,pattern = "Abd"),1,6)


my_data("sau_species") %>% 
  filter(taxon_key %in% file_to_read) %>% 
  View()


```


## Per Species Data


```{r sppfx, eval = F, echo = F}


spp_fx <- function(taxon){
  
  to_read <- paste0(taxon,"Catch.RData")
  
  for(m in 1:length(scen)){
    
    file_to_read <- paste0(scen[m],"/",to_read)
    
    if(file.exists(file_to_read)){
      
      load(file_to_read)
      
      # Transform it to same name sppMCPfnl
      # suppressWarnings(
      # if(exists("data")){
      spp_data <- as.data.frame(data) %>%
        rowid_to_column("index")
      rm(data)
      # }
      
      colnames(spp_data) <- c("index",(seq(1951,2100,1)))
      
      early_data <- spp_data %>% 
        gather("year","value",`1951`:`2100`) %>% 
        filter(index %in% cmar_grid$index) %>% 
        mutate(period = ifelse(year < 2060 & year > 2041,"2060_mid",
                               ifelse(year < 2040 & year > 2021,"2040_ear",
                                      ifelse(year < 2100 & year > 2081,"2100_end",
                                             ifelse(year < 2014 & year > 1995,"2014_hist",
                                             NA)
                               )
                               )
                               
        )
        ) %>% 
        filter(!is.na(period)) %>% 
        left_join(cmar_grid,
                  by = "index",
                  relationship = "many-to-many") %>% 
        group_by(region,year,period) %>% 
        # Sum total catch per eez per year
        summarise(eez_catch = sum(value, na.rm = T),.groups = "drop") %>% 
        group_by(region,period) %>% 
        # Average yearly data
        summarise(mcp = mean(eez_catch,na.rm = T),.groups = "drop") %>% 
        mutate(
          taxon_key = taxon,
          esm = str_sub(file_to_read,65,68),
          ssp = ifelse(str_sub(file_to_read,69,70) == 26,"ssp126","ssp585"),
          scen = str_sub(file_to_read,73,74)
        )
      
      
      # Join data for all three models
      if(m == 1){
        partial_output <- early_data
      }else{
        partial_output <- bind_rows(partial_output,early_data)
      }
      
    }else{
      partial_output
      print(file_to_read)
    }
  }
  
  # print(paste(unique(partial_output$esm)))
  # print(paste(unique(partial_output$scen)))
  # print(paste(unique(partial_output$ssp)))
  # print(paste(unique(partial_output$region)))
  
  # Average ESMs +- SD
  final_output <- partial_output %>% 
    group_by(taxon_key,region,period,ssp,scen) %>% 
    summarise(mean_mcp_esm = mean(mcp, na.rm =T),
              sd_mcp_esm = sd(mcp, na.rm =T),
              .groups = "drop") %>% 
    # remove cases where all three periods are 0
    group_by(taxon_key,region,period,ssp) %>% 
    filter(any(mean_mcp_esm != 0))
  
  
  
  name <- paste0(taxon,"_mcp_period.csv")
  print(paste(unique(name)))
  
  write_csv(final_output,
            my_path("R","processed/species/period_data/",name))
  
  
} # Close function

```


```{r}

# species list
etpmc_spp <- read.table("~/Library/CloudStorage/GoogleDrive-jepa88@gmail.com/My Drive/lenfest_mpa_project/data/species (1)/EtpSppList10.txt", quote="\"", comment.char="") %>% 
  rename(taxon_key = V1) %>% 
  left_join(dbem_spp)

# ran_spp <- list.files(my_path("R","dbem_outputs/Rdata/",system = "juliano"))

ran_spp <- str_sub(ran_spp,1,6)

scen <-
  my_path("R","dbem_outputs/Rdata",
                list_files = "paths",
                system = "juliano")


dbem_spp <- dbem_spp %>% 
  filter(!taxon_key %in% ran_spp)

library(parallel)

mclapply(etpmc_spp$taxon_key, spp_fx, mc.cores = detectCores() - 4)



```



## Per species percentage change SQ


This analysis estimates the species percentage change relative to the SQ scenario


```{r}

sau_sf <- my_sf("SAU") %>% 
  filter(name %in% c("Costa Rica (Pacific)","Colombia (Pacific)","Panama (Pacific)","Galapagos Isl. (Ecuador)", "Ecuador"))

cmar_sf <- read_sf(paste0(data_path,"spatial/cmar_capas/all_cmar_mpas.shp"))


scen_dif_fx <- function(taxon,var = "abd"){

  name <- paste0(taxon,"_",var,"_period.csv")
  
  spp_data <-
    my_path("R","processed/species/period_data/",name,read = T) %>% 
    select(-sd_mcp_esm) %>% 
    pivot_wider(names_from = scen, values_from = mean_mcp_esm) %>% 
    mutate(
      dif_no_reg = my_chng(sq,nr),
      dif_reg_cons = my_chng(sq,rc),
      dif_reg_imp = my_chng(sq,ri),
      per_reg_fish = my_chng(sq,rp)
    ) %>% 
    select(
      taxon_key:ssp,region, dif_no_reg:per_reg_fish
    ) %>% 
    gather("scen","per_change",dif_no_reg:per_reg_fish) %>% 
    filter(period != "2014_hist")
  
  
  # species map
  map_t <- ggplot() +
    geom_sf(data = sau_sf %>% select(region = name) %>%  left_join(spp_data) %>% filter(ssp == "ssp585"),
            aes(fill = per_change),
            color = "grey"
    ) +
    geom_sf(data = cmar_sf %>%  left_join(spp_data) %>% filter(ssp == "ssp585"),
            aes(fill = per_change),
            color = "black"
    ) +
    facet_grid(period~scen) +
    scale_fill_gradient2() +
    ggtitle(etpmc_spp %>% filter(taxon_key == taxon) %>% pull(common_name)) +
    my_ggtheme_m("Reg",facet_tl_s = 6,ax_tl_s = 6,ax_tx_s = 3,leg_tl_s = 3,leg_tx_s = 3) +
    theme(legend.text = element_text(size = 6),
          legend.title = element_text(size = 6),
          legend.key.height = unit(0.2, "line"),
          title = element_text(size = 6)
          )
  
  
  map_name <- paste0(unique(spp_data$taxon_key),"_",var,"_scen_diff.png")
  
  ggsave(
    my_path("R","figures/scen_diff/species/",map_name),
    map_t,
    height = 3,
    width = 4)
  
  
}


scen_dif_fx(600077)


lapply(etpmc_spp$taxon_key, scen_dif_fx)


```





```{r}



agg_fx <- function(scenario, category){
  
  file_to_read <- list.files(my_path("R",scenario),full.names = T,pattern = category)
  
  for(i in 1:length(file_to_read)){
    # print(i)
    load(file_to_read[i])
    
    # Transform it to df
    spp_data <- as.data.frame(data) %>% 
      rowid_to_column("index") %>% 
      filter(index %in% cmar_grid$index)
    colnames(spp_data) <- c("index",(seq(1951,2100,1)))
    rm(data) # remove data for computing power
    
    
    partial_data <- spp_data %>% 
      gather("year","value",`1951`:`2100`)
    
    # Join data for all three models
    if(i == 1){
      complete_output <- partial_data
    }else{
      
      complete_output <- left_join(complete_output,partial_data,
                                   by = c("index","year")
      ) %>% 
        mutate_at(
          .vars = c("value.x","value.y"),
          .funs = replace_na,0
        ) %>% 
        mutate(sum_value = value.x + value.y) %>% 
        select(index,year,value = sum_value)
      
    }
    
  } # close for loop in i for species
  
  final_df <- complete_output %>% 
    mutate(
      esm = str_sub(scenario,3,6),
      rcp = str_sub(scenario,7,8),
      scenario = str_sub(scenario,str_count(scenario)-2,str_count(scenario))
    )
  
  
  return(final_df)
  
}



```

# Per scenario

## Create Data Estimate percentage change

```{r}

scen <-
  my_path("R","dbem_outputs/Rdata",
                list_files = "paths",
                system = "juliano")

sqb_scen_df <- agg_fx(scenario = scen, category =  "Abd")

sc_name <- str_sub(scen,str_count(scen)-2,str_count(scen))
ssp <- str_sub(scen,7,8)

cmar_sf <- read_sf(paste0(data_path,"spatial/cmar_capas/all_cmar_mpas.shp"))

# Estimate historical MCP data for all species
early_data <- sqb_scen_df %>% 
  mutate(period = ifelse(year < 2014 & year > 1995,"present",NA)) %>% 
  filter(!is.na(period)) %>% 
  # left_join(cmar_grid,
  #           by = "index") %>%
  # filter(!is.na(eez_id)) %>%
  # group_by(index,year,period) %>%
  # Sum total catch per eez per year
  # summarise(eez_catch = sum(value, na.rm = T),.groups = "drop") %>% 
  group_by(index,period) %>% 
  # Average yearly data
  summarise(mean_temp_value = mean(value,na.rm = T),.groups = "drop") %>% 
  select(-period)

# Estimate percentage change in future data for all species
future_data <-  sqb_scen_df %>% 
  mutate(period = ifelse(year < 2060 & year > 2041,"2060_mid",
                         ifelse(year < 2040 & year > 2021,"2040_ear",
                                ifelse(year < 2100 & year > 2081,"2100_end",
                                       NA)
                         )
                         
  )
  ) %>% 
  filter(!is.na(period)) %>% 
  # left_join(regional_grid,
  #           by = "index") %>%
  # filter(!is.na(eez_id)) %>%
  group_by(index,period) %>%
  # Sum total catch per eez per year
  summarise(mean_temp_value_fut = mean(value, na.rm = T),.groups = "drop") %>%
  left_join(early_data,
            by = "index") %>%
  # spread(period,mean_catch) %>% 
  mutate(
    per_change = ifelse(mean_temp_value == 0 & mean_temp_value_fut > 0,100, 
                        round((mean_temp_value_fut-mean_temp_value)/mean_temp_value*100)
    ),
    per_change_scale = ifelse(abs(per_change) > 50, sign(per_change) * 50, per_change)
  ) %>% 
  filter(!is.na(per_change))

# Join data for all three models
#   if(m == 1){
#     models_output <- future_data
#   }else{
#     models_output <- bind_rows(models_output,future_data)
#   }
# } # close for loop in m for models


# # Average results per ESM
# final_output <- models_output %>% 
#   group_by(eez_name,year,ssp) %>% 
#   summarise(mean_per_change = mean(per_change, na.rm =T),
#             sd_per_change = sd(per_change, na.rm =T)) %>% 
#   group_by(eez_name,ssp) %>% 
#   mutate(
#     per_change_rm = round(zoo::rollmean(
#       mean_per_change,
#       k = 10, 
#       fill = NA, 
#       align = "right")
#     )
#   ) %>% 
#   filter(!is.na(per_change_rm))

# Save data
# write_csv(final_output,
# my_path("R",name = "aggregated_data.csv"))

# }
# }


```

## Map

```{r}


map <- future_data %>% 
  left_join(cmar_grid) %>% 
  ggplot() +
  geom_tile(
    aes(
      x = lon,
      y = lat,
      fill = per_change_scale
    )
  ) +
  # geom_sf_label(data = cmar_sf, aes(label = mpa_abrev)) +
  my_land_map()+ 
  scale_fill_gradient2() +
  geom_sf(data = cmar_sf, aes(), color = "black", fill = "transparent") +
  coord_sf(
    xlim = c(-95,-77),
    ylim = c(-4,9)
  ) +
  facet_wrap(~period) +
  theme(legend.position = "bottom")

ggsave(
  paste0(results_path,"/scenario_map_",sc_name,"_",ssp,".jpg"),
  map,
  width = 14)

```


## Boxplot

```{r}


future_data %>% 
  left_join(cmar_grid) %>% 
  # View()
  ggplot() +
  facet_wrap(~period) +
  # geom_jitter(aes(
  #   x = status,
  #   y = per_change_scale
  # ),
  # color="grey30", size=0.4, alpha=0.9) +
  geom_boxplot(
    aes(
      x = status,
      y = per_change_scale,
      fill = status
    )
  ) +
  theme_ipsum() +
  scale_fill_viridis(discrete = TRUE, alpha=0.6) +
  theme(legend.position = "")


ggsave(
  paste0(results_path,"/status_boxplot_",sc_name,"_",ssp,".jpg"),
  last_plot(),
  width = 9,
  height = 8
)

```

```{r}


future_data %>% 
  left_join(mpas_grid) %>% 
  filter(!is.na(mpa_abrev)) %>% 
  # View()
  ggplot() +
  geom_jitter(aes(
    x = reorder(mpa_abrev, per_change_scale, FUN = median),
    y = per_change_scale,
    color = status
  ),
  size=0.4, alpha=0.5) +
  geom_boxplot(
    aes(
      x = reorder(mpa_abrev, per_change_scale, FUN = median),
      y = per_change_scale,
      fill = mpa_abrev
    )
  ) +
  theme_ipsum() +
  scale_fill_viridis(discrete = TRUE, alpha=0.3) +
  # scale_color_viridis_d(direction = -1,option = "A") +
  theme(
    axis.text.x = element_text(angle = 45,hjust = 1),
    legend.position = ""
  )+
  facet_wrap(~period)


ggsave(
  paste0(results_path,"/mpa_boxplot_",sc_name,"_",ssp,".jpg"),
  last_plot(),
  width = 14)

```

# All scenarios

```{r, eval = F}

scenarios <- list.files(my_path("R"))

all_scen <- bind_rows(
  lapply(scenarios, agg_fx, category = "Abd")
)

unique(all_scen$esm)
unique(all_scen$rcp)
unique(all_scen$scenario)

# write_csv(all_scen,
#           paste0(results_path,"/full_data.csv"),
#           )

```

## Estimate percentage change

```{r}


all_scen <- read_csv(paste0(results_path,"/tables/full_data.csv"))


# Estimate historical MCP data for all species
early_data <- all_scen %>% 
  mutate(period = ifelse(year < 2014 & year > 1995,"present",NA)) %>% 
  filter(!is.na(period)) %>% 
  group_by(index,period,rcp,scenario) %>% 
  # Average yearly data
  summarise(mean_temp_value = mean(value,na.rm = T),.groups = "drop") %>% 
  select(-period)

# Estimate percentage change in future data for all species
future_data <-  all_scen %>% 
  mutate(period = ifelse(year < 2060 & year > 2041,"2060_mid",
                         ifelse(year < 2040 & year > 2021,"2040_ear",
                                ifelse(year < 2100 & year > 2081,"2100_end",
                                       NA)
                         )
  )
  ) %>% 
  filter(!is.na(period)) %>% 
  group_by(index,period,rcp,scenario) %>% 
  # Sum total catch per eez per year
  summarise(mean_temp_value_fut = mean(value, na.rm = T),.groups = "drop") %>%
  left_join(early_data,
            by = c("index","rcp","scenario")
  ) %>%
  mutate(
    per_change = ifelse(mean_temp_value == 0 & mean_temp_value_fut > 0,100, 
                        round((mean_temp_value_fut-mean_temp_value)/mean_temp_value*100)
    ),
    per_change_scale = ifelse(abs(per_change) > 50, sign(per_change) * 50, per_change)
  ) %>% 
  # filter(!is.na(per_change),
  #        period != "2100_end")
  filter(!is.na(per_change),
         period != "2100_end")


unique(future_data$rcp)
unique(future_data$scenario)

```

## Map

```{r}

ssp <- 26

map <- future_data %>% 
  filter(rcp == ssp) %>% 
  left_join(cmar_grid) %>% 
  ggplot() +
  geom_tile(
    aes(
      x = lon,
      y = lat,
      fill = per_change_scale
    )
  ) +
  # geom_sf_label(data = cmar_sf, aes(label = mpa_abrev)) +
  my_land_map()+ 
  scale_fill_gradient2() +
  geom_sf(data = cmar_sf, aes(), color = "black", fill = "transparent") +
  coord_sf(
    xlim = c(-95,-77),
    ylim = c(-4,9)
  ) +
  facet_wrap(period~scenario,
             nrow = 2) +
  theme(legend.position = "bottom")

ggsave(
  paste0(results_path,"/figures/scenario_map_all_",ssp,".jpg"),
  map,
  width = 14)


```

## Boxplot

```{r}


future_data %>% 
  filter(rcp == ssp) %>% 
  left_join(cmar_grid) %>% 
  ggplot() +
  facet_wrap(~period) +
  geom_boxplot(
    aes(
      x = scenario,
      y = per_change_scale,
      fill = scenario
    )
  ) +
  theme_ipsum() +
  scale_fill_viridis(discrete = TRUE, alpha=0.6) +
  theme(legend.position = "") +
  facet_wrap(period~status,
             nrow = 2,
             scale = "free")


ggsave(
  paste0(results_path,"/figures/status_boxplot_all_",ssp,".jpg"),
  last_plot(),
  width = 9,
  height = 8
)

```



```{r}

future_data %>% 
  left_join(mpas_grid) %>% 
  filter(!is.na(mpa_abrev)) %>% 
  filter(rcp == ssp) %>% 
  ggplot() +
  geom_jitter(aes(
    x = reorder(scenario, per_change_scale, FUN = median),
    y = per_change_scale,
    color = status
  ),
  size=0.4, alpha=0.5) +
  geom_boxplot(
    aes(
      x = reorder(scenario, per_change_scale, FUN = median),
      y = per_change_scale,
      fill = mpa_abrev
    )
  ) +
  scale_y_continuous(limits = c(-20,15)) +
  theme_ipsum() +
  scale_fill_viridis(discrete = TRUE, alpha=0.3) +
  theme(
    axis.text.x = element_text(angle = 45,hjust = 1),
    legend.position = ""
  ) +
  # facet_wrap(mpa_abrev~period,
  #            nrow = 2,
  #            scale = "free")
  facet_grid(period~mpa_abrev)


ggsave(
  paste0(results_path,"/figures/mpa_boxplot_all","_",ssp,".jpg"),
  last_plot(),
  width = 14,
  heigh = 10)

```
# Per MPA

```{r, eval = F}

scenarios <- list.files(my_path("R"))

all_scen <- bind_rows(
  lapply(scenarios, agg_fx, category = "Abd")
)

unique(all_scen$esm)
unique(all_scen$rcp)
unique(all_scen$scenario)

# write_csv(all_scen,
#           paste0(results_path,"/full_data.csv"),
#           )

```

## Estimate percentage change

```{r}


all_scen <- read_csv(paste0(results_path,"/tables/full_data.csv"))


# Estimate historical MCP data for all species
early_data <- all_scen %>% 
  left_join(cmar_grid) %>% 
  mutate(period = ifelse(year < 2014 & year > 1995,"present",NA)) %>% 
  filter(!is.na(period)) %>% 
  group_by(mpa_abrev,year,period,rcp,scenario) %>% 
  # Average yearly data
  summarise(sum_temp_value = sum(value,na.rm = T),.groups = "drop") %>% 
  group_by(mpa_abrev,period,rcp,scenario) %>% 
  # Average yearly data
  summarise(mean_temp_value = mean(sum_temp_value,na.rm = T),.groups = "drop") %>% 
  select(-period)

# Estimate percentage change in future data for all species
future_data <-  all_scen %>% 
  mutate(period = ifelse(year < 2060 & year > 2041,"2060_mid",
                         ifelse(year < 2040 & year > 2021,"2040_ear",
                                ifelse(year < 2100 & year > 2081,"2100_end",
                                       NA)
                         )
  )
  ) %>% 
  left_join(cmar_grid) %>% 
  filter(!is.na(period)) %>% 
  group_by(mpa_abrev,year,period,rcp,scenario) %>% 
  # Sum total catch per eez per year
  summarise(mean_temp_value_fut = sum(value, na.rm = T),.groups = "drop") %>%
  group_by(mpa_abrev,period,rcp,scenario) %>% 
  # Sum total catch per eez per year
  summarise(mean_temp_value_fut = mean(mean_temp_value_fut, na.rm = T),.groups = "drop") %>%
  left_join(early_data,
            by = c("mpa_abrev","rcp","scenario")
  ) %>%
  mutate(
    per_change = ifelse(mean_temp_value == 0 & mean_temp_value_fut > 0,100, 
                        round((mean_temp_value_fut-mean_temp_value)/mean_temp_value*100)
    ),
    per_change_scale = ifelse(abs(per_change) > 50, sign(per_change) * 50, per_change)
  ) %>% 
  filter(!is.na(per_change))


unique(future_data$rcp)
unique(future_data$scenario)

```

## Map

```{r}

ssp <- 26

mpa <- unique(cmar_grid$mpa_abrev)

for(i in 2:11){
  
  mpa_selected <- mpa[i]
  
  mpa_data <- cmar_grid %>% 
    filter(mpa_abrev == mpa_selected)
  
  path_mpa <- st_read(paste0(data_path,"spatial/cmar_capas/",mpa_selected,".shp")) %>% 
    st_transform(4326)
  
  map <- future_data %>% 
    filter(rcp == ssp) %>% 
    left_join(mpa_data) %>% 
    filter(!is.na(lon)) %>% 
    ggplot() +
    geom_tile(
      aes(
        x = lon,
        y = lat,
        fill = per_change_scale
      )
    ) +
    # geom_sf_label(data = cmar_sf, aes(label = mpa_abrev)) +
    # my_land_map()+ 
    scale_fill_gradient2() +
    # coord_sf(
    # xlim = c(-95,-77),
    # ylim = c(-4,9)
    # ) +
    geom_sf(data = path_mpa, aes(), color = "black", fill = "transparent") +
    facet_wrap(period~scenario,
               nrow = 3) +
    theme(legend.position = "bottom") +
    ggtitle(paste(mpa_selected,ssp))
  
  ggsave(
    paste0(results_path,"/figures/mpa_level/mpa_scenario_map_all_",ssp,"_",mpa_selected,".jpg"),
    map,
    width = 14)
  
  ## Boxplot
  future_data %>% 
    filter(rcp == ssp) %>% 
    left_join(mpa_data) %>% 
    ggplot() +
    facet_wrap(~period) +
    geom_boxplot(
      aes(
        x = scenario,
        y = per_change_scale,
        fill = scenario
      )
    ) +
    theme_ipsum() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    theme(legend.position = "") +
    facet_wrap(period~status,
               nrow = 3,
               scale = "free") +
    ggtitle(paste(mpa_selected,ssp))
  
  
  ggsave(
    paste0(results_path,"/figures/mpa_level/status_boxplot_all_",ssp,"_",mpa_selected,".jpg"),
    last_plot(),
    width = 9,
    height = 8
  )
  
  # Boxplor status
  
  future_data %>% 
    left_join(mpa_data) %>% 
    filter(!is.na(mpa_abrev)) %>% 
    filter(rcp == ssp) %>% 
    ggplot() +
    geom_jitter(aes(
      x = reorder(scenario, per_change_scale, FUN = median),
      y = per_change_scale,
      color = status
    ),
    size=0.4, alpha=0.5) +
    geom_boxplot(
      aes(
        x = reorder(scenario, per_change_scale, FUN = median),
        y = per_change_scale,
        fill = mpa_abrev
      )
    ) +
    # scale_y_continuous(limits = c(-20,15)) +
    theme_ipsum() +
    scale_fill_viridis(discrete = TRUE, alpha=0.3) +
    theme(
      axis.text.x = element_text(angle = 45,hjust = 1),
      legend.position = ""
    ) +
    facet_grid(period~mpa_abrev) +
    ggtitle(paste(mpa_selected,ssp))
  
  
  ggsave(
    paste0(results_path,"/figures/mpa_level/mpa_boxplot_all",ssp,"_",mpa_selected,".jpg"),
    last_plot(),
    width = 14,
    heigh = 10)
  
}

```
