---
title: "data for renato"
author: "Juliano Palacios-Abrantes"
date: "`r Sys.Date()`"
output: html_document
---

# Objective 

This sceript is used to get the data for Renato's analysis. It will calculate the proportion of species in each EEZ and the percentage change over time. It will also get the life history data for the species.

It is not used in the main manuscript

```{r setup, include = F}

library(MyFunctions)

my_lib(c(
  # For grid estimation and species selection
  "spatialEco","tidyverse", 
  # For collaborative ease
  "here",
  "readr",
  "janitor",
  "readxl",
  "parallel"
))

# Change paths to your computer

data_path <- "~/Library/CloudStorage/GoogleDrive-jepa88@gmail.com/My Drive/lenfest_mpa_project/data/"
results_path <- "~/Library/CloudStorage/GoogleDrive-jepa88@gmail.com/My Drive/lenfest_mpa_project/manuscripts/scenarios/results/figures"

```


# Load data 

```{r}

# library(readxl)
sau_combo <- read_excel("~/Library/CloudStorage/OneDrive-UBC/Data/Spatial/SAU/EEZ-FAO-Country-Combo.xlsx")
# View(sau_combo)

# mPA grids
# Load Grid data
grid_path <- paste0(data_path,"spatial/gridded/all_mpa_grid_fe.csv")
mpas_grid <- read_csv(grid_path) %>% 
  rename(mpa_abrev = mpa) %>% 
  distinct()


# list of data paths
dbem_data <- list.files(my_path("R","results_f0"),full.names = T)

# List of species
file_list <- list.files(my_path("R","results_f0/c6gfdl26F0sq"),full.names = F)

# Get high seas
cmar_grid <- my_data("dbem_coords") %>% 
  filter(lat < 12 & lat > -5 & lon > -95.5 & lon < -71) %>% 
  left_join(mpas_grid) %>% 
  mutate(status = ifelse(is.na(status),"non_protected",status)) %>% 
  left_join(my_data("sau_index")) %>% 
  filter(eez_name %in% c("Colombia (Pacific)",
                         "Panama (Pacific)",
                          "Costa Rica (Pacific)",
                          "Galapagos Isl. (Ecuador)",
                          "Ecuador",
                         "High seas"))

ggplot(cmar_grid) +
  geom_tile(
    aes(
      x = lon,
      y = lat,
      fill = eez_name
    )
  )
```

# Proportion estimates


```{r}

# taxon_key <- dbem_data[3]

prop_fx <- function(taxon_path){
  
  taxon <- unique(str_sub(taxon_path,96,101))
  print(taxon)
  for(i in 1:6){
  
    taxon_path_load <- taxon_path[i]
    
  load(taxon_path_load)
  
  
  esm <- unique(str_sub(taxon_path_load,85,88))
  ssp <- unique(str_sub(taxon_path_load,89,90))
  
  
  spp_data <- as.data.frame(data) %>% 
    rowid_to_column("index")
  rm(data)
  colnames(spp_data) <- c("index",(seq(1951,2100,1)))
  
  
  partial <- spp_data %>% 
    select(`1995`:`2014`,`2020`:`2039`,`2040`:`2059`,`2081`:`2100`) %>% 
    rowid_to_column("index") %>% 
    filter(index %in% cmar_grid$index) %>% 
    gather(year,"abd",`1995`:`2059`) %>% 
    left_join(cmar_grid) %>% 
    mutate(period = ifelse(year < 2014 & year > 1995,"1995_2014_present",
                           ifelse(year < 2039 & year > 2020,"2020_2039_ear",
                                  ifelse(year < 2059 & year > 2040,"2040_2059_mid",
                                         "2081_2100_end"))
    )
    ) %>% 
    filter(!is.na(eez_id)) %>% 
    # Aggregate abd by EEZ
    group_by(year,eez_id,eez_name,period) %>% 
    summarise(eez_abd = sum(abd, na.rm = T)) %>% 
    # Mean abd by period
    group_by(eez_id,eez_name,period) %>% 
    summarise(mean_eez_abd = mean(eez_abd, na.rm = T))
  
  
  totals <- partial %>% 
    group_by(period) %>% 
    summarise(tot_abd = sum(mean_eez_abd,na.rm = T))
  
  partial_df <- partial %>% 
    left_join(totals,
              by = "period") %>% 
    mutate(eez_proportion = mean_eez_abd/tot_abd,
           taxon_key = taxon,
           esm = esm,
           ssp = ssp)
  
  
  
  if(i == 1){
    final_df <- partial_df
  }else{
    final_df <- bind_rows(final_df,partial_df)
  }
  
  
  }
  
  # Average_esms
  final_df_average <- final_df %>% 
    group_by(taxon_key,eez_id,eez_name,period,ssp) %>% 
    # summarise_if(is.numeric,
    #              c("mean" = mean,
    #                "sd" = sd)
    #              ) %>% 
    summarise(
      mean_proportion = mean(eez_proportion, na.rm = T),
      sd_proportion = sd(eez_proportion, na.rm = T)
    )
  
  # save data
  df_name <- paste0(taxon,"_prop.csv")
  write_csv(final_df_average,
  my_path("R","socio_ecol/prop/",df_name)
  )
  
  # save plot
  bar_plot <- final_df_average %>% 
  ggplot() +
  geom_bar(
    aes(
      x = period,
      y = mean_proportion,
      color = eez_name,
      fill = eez_name
    ),
    stat = "identity"
  ) +
  facet_wrap(~ssp)
  
  plot_name <- paste0(taxon,"_prop.png")
  ggsave(plot = bar_plot,
         filename = my_path("R","socio_ecol/plots/",plot_name),
         width = 10)
  
}


suppressWarnings(
  suppressMessages(
    for(i in 1:length(file_list)){
      taxon_path <- paste0(dbem_data,"/",file_list[i])
      
      prop_fx(taxon_path)
      
    }
  )
)


```

## Check percentage changes

```{r}

prop_path <- list.files(my_path("R","socio_ecol/prop/"),full.names = T)
dbem_spp <- my_data("dbem_species")

prop_data <- bind_rows(
  lapply(prop_path, read_csv)
)

prop_diff <- prop_data %>% 
  select(-sd_proportion) %>% 
  filter(ssp == 85) %>% 
  mutate(mean_proportion = mean_proportion*100) %>% 
  spread(period,mean_proportion) %>% 
  mutate(
    dif_ear = `2020_2039_ear`-`1995_2014_present`,
    dif_mid = `2040_2059_mid`-`1995_2014_present`,
    dif_end= `2081_2100_end`-`1995_2014_present`
  ) %>% 
  left_join(dbem_spp)

```



```{r}

prop_diff %>% 
  gather("difference","value",dif_ear:dif_end) %>% 
ggplot() +
  geom_histogram(
    aes(
      x = value
    )
    )+
      facet_wrap(~difference)
    

```

# Life history

```{r get_salmon_lif_history}

# Get life history data
etpmc_spp <- read.table("~/Library/CloudStorage/GoogleDrive-jepa88@gmail.com/My Drive/lenfest_mpa_project/data/00 species/dbem_spp/EtpSppList10.txt", quote="\"", comment.char="") %>% 
  rename(taxon_key = V1)


for(i in 1:43){
  
  file <- paste0(etpmc_spp$taxon_key,".txt")[i]
  
  path_read <- my_path("G","Species/TaxonDataC/",file)
  
  partial <- read_delim(path_read,
                        delim = "\t", escape_double = FALSE, 
                        col_names = FALSE, trim_ws = TRUE) %>% 
    mutate(taxon_key = etpmc_spp$taxon_key[i]) %>% 
    slice(-1,-2)
  
  if(i == 1){
    final <- partial
  }else{
    final <- bind_rows(partial,final)
  }
  
}


final %>% 
  filter(X1 %in% c("IntrinsicR","Linf","VBonK","LwA","LwB")) %>% 
  select("variable" = X1,
         "value" = X2,
         taxon_key) %>% 
  filter(variable == "IntrinsicR") %>% 
  left_join(my_data("dbem_species")) %>%
  View()
  write_csv("~/Library/CloudStorage/GoogleDrive-jepa88@gmail.com/My Drive/lenfest_mpa_project/data/05 econ/life_history_etp_spp.csv")

  
  # Updates of estimate
  
get_k <- function(x){

xx <- popgrowth(x) %>% 
  select(Species,r2,K,M)
 
return(xx) 
}

k_estimates_df <- bind_rows(
  lapply(etpmc_spp %>% 
           left_join(
             my_data("dbem_species")) %>% 
           pull(taxon_name)
           , get_k
  )
)


k_estimates_df %>% 
  group_by(Species) %>%
  summarise(
    mean_k = mean(K, na.rm = T),
    # sd_k = sd(K, na.rm = T),
    mean_m = mean(M, na.rm = T),
    # sd_m = sd(M, na.rm = T),
  ) %>% 
  mutate(
    r_jensen = mean_k*1.5,
    r_m = mean_m*2,
    r_final = ifelse(r_jensen > 0 & r_m != "NaN",(r_jensen + r_m)/2,
                    ifelse(r_jensen > 0,r_jensen,r_m)
    )
  ) %>% 
  View()

```


# K

```{r}

taxon_file <- file_list[1]

get_k_fx <- function(taxon_file){
  
  
  taxon_path <- paste0(dbem_data,"/",taxon_file)
  
  taxon <- unique(str_sub(taxon_path,81,86))
  print(taxon)
  for(i in 1:6){
  
    taxon_path_load <- taxon_path[i]
    
  load(taxon_path_load)
  
  
  esm <- unique(str_sub(taxon_path_load,70,73))
  ssp <- unique(str_sub(taxon_path_load,74,75))
  
  
  spp_data <- as.data.frame(data) %>% 
    rowid_to_column("index")
  rm(data)
  colnames(spp_data) <- c("index",(seq(1951,2100,1)))

  partial <- spp_data %>% 
    select(`1995`:`2014`,`2020`:`2039`,`2040`:`2059`,`2081`:`2100`) %>% 
    rowid_to_column("index") %>% 
    filter(index %in% cmar_grid$index) %>% 
    gather(year,"abd",`1995`:`2059`) %>% 
    left_join(cmar_grid,
              by = "index") %>% 
    mutate(period = ifelse(year < 2014 & year > 1995,"1995_2014_present",
                           ifelse(year < 2039 & year > 2020,"2020_2039_ear",
                                  ifelse(year < 2059 & year > 2040,"2040_2059_mid",
                                         "2081_2100_end"))
    )
    ) %>% 
    filter(!is.na(eez_id)) %>% 
    # Aggregate abd by EEZ
    group_by(year,period) %>% 
    summarise(eez_abd = sum(abd, na.rm = T)) %>% 
    # Mean abd by period
    group_by(period) %>% 
    summarise(mean_cmar_k = mean(eez_abd, na.rm = T)) %>% 
    mutate(
      taxon_key = taxon,
      ssp = ssp,
      esm = esm)
  
  if(i == 1){
    final_df <- partial
  }else{
    final_df <- bind_rows(final_df,partial)
  }
  
  output_df <- final_df %>% 
    group_by(taxon_key,period,ssp) %>%
    summarise(
      sd_cmar_k = sd(mean_cmar_k, na.rm = T),
      mean_cmar_k = mean(mean_cmar_k, na.rm = T)
    ) %>% 
    select(taxon_key,period,ssp,mean_cmar_k,sd_cmar_k)
  
  }
  
  return(output_df)
}
  
  
  
# list of data paths
dbem_data <- list.files(my_path("R","dbem_outputs/results_f0",system = "juliano"),full.names = T)

# List of species
file_list <- list.files(my_path("R","dbem_outputs/results_f0/c6gfdl26F0sq",system = "juliano"),full.names = F)

# taxon_path <- paste0(dbem_data,"/",file_list[i])


# get_k_fx(taxon_path)

suppressWarnings(
  suppressMessages(
      test <- bind_rows(
        lapply(file_list, get_k_fx)
      )
  )
)


write_csv(test,
        my_path("R","socio_ecol/","k_estimates.csv")
        )

```

